# Generated by Django 4.1.4 on 2023-01-22 08:41

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_userprofile_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.IntegerField()),
                ('district', models.CharField(max_length=50)),
                ('unit_type', models.CharField(max_length=50)),
                ('unit_name', models.CharField(max_length=50)),
                ('district_c', models.IntegerField()),
                ('shape_leng', models.FloatField()),
                ('shape_area', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
