# Generated by Django 4.1.4 on 2023-01-22 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_counties_alter_localaddress_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counties',
            name='dis',
            field=models.IntegerField(null=True),
        ),
    ]
