# Generated by Django 4.1.4 on 2023-02-03 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_edge_node_delete_counties_delete_roads_edge_end_node_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nodes_and_edges_created', models.BooleanField(default=False)),
            ],
        ),
    
    ]
