# Generated by Django 4.1.4 on 2023-03-07 03:05

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_adjacencylist_delete_roads_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('length_m', models.FloatField()),
                ('lineid', models.BigIntegerField()),
                ('lat_n1', models.FloatField()),
                ('long_n1', models.FloatField()),
                ('long_n2', models.FloatField()),
                ('lat_n2', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
            ],
        ),
       
    ]
