# Generated by Django 4.1.4 on 2023-03-07 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_delete_roads_alter_road_name'),
    ]

    operations = [
       
        migrations.RemoveField(
            model_name='edge',
            name='cost',
        ),
    ]
