# Generated by Django 4.1.4 on 2023-01-16 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipper', '0001_initial'),
        ('orders', '0004_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shippers',
            field=models.ManyToManyField(blank=True, to='shipper.shipper'),
        ),
    ]
