# Generated by Django 4.1.4 on 2023-01-17 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_shiporder_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shiporder_status',
        ),
        migrations.AddField(
            model_name='shiporder',
            name='shiporder_status',
            field=models.CharField(default='New', max_length=50),
        ),
    ]
