# Generated by Django 4.1.4 on 2023-01-17 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_remove_order_shiporder_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiporder',
            name='shipping_number',
            field=models.CharField(default='sno', max_length=20),
        ),
        migrations.AlterField(
            model_name='shiporder',
            name='shiporder_status',
            field=models.CharField(choices=[('New', 'New'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='New', max_length=50),
        ),
    ]
