# Generated by Django 4.1.4 on 2023-01-24 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_shiporder_shipping_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiporder',
            name='package_volume',
            field=models.FloatField(blank=True, default='0.00'),
        ),
    ]
