# Generated by Django 4.1.4 on 2023-01-24 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_shiporder_package_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiporder',
            name='package_volume',
            field=models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=6),
        ),
    ]
