# Generated by Django 4.1.4 on 2023-01-24 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_shiporder_package_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiporder',
            name='package_volume',
            field=models.FloatField(blank=True, default='0.00'),
        ),
    ]
